
export const COUNTRIES = [
  { name: "Japan", flag: "images/japan-flag.png" },
  { name: "Brazil", flag: "images/brazil-flag.png" },
  { name: "Egypt", flag: "images/egypt-flag.png" },
  { name: "France", flag: "images/france-flag.png" },
  { name: "Germany", flag: "images/germany-flag.png" },
  { name: "Italy", flag: "images/italy-flag.png" },
  { name: "United Kingdom", flag: "images/united kingdom-flag.png" },
  { name: "United States", flag: "images/us-flag.webp" },
  { name: "Canada", flag: "images/canada-flag.png" },
  { name: "Turkey", flag: "images/turkey-flag.png" },
  { name: "China", flag: "images/china-flag.png" },
  { name: "South Korea", flag: "images/south korea-flag.png" },
  { name: "India", flag: "images/india-flag.png" },
  { name: "Russia", flag: "images/russia-flag.jpg" },
  { name: "Australia", flag: "images/australia-flag.png" },
  { name: "Mexico", flag: "images/mexico-flag.png" },
  { name: "Argentina", flag: "images/argentina-flag.png" },
  { name: "Spain", flag: "images/spain-flag.png" },
 { name: "Saudi Arabia", flag: "images/saudi arabia-flag.png" },
  { name: "South Africa", flag: "images/south africa-flag.png" },
  { name: "Nigeria", flag: "images/nigeria-flag.png" },
  { name: "Sweden", flag: "images/sweden-flag.png" },
  { name: "Norway", flag: "images/norway-flag.png" },
  { name: "Greece", flag: "images/greece-flag.png" },
];
