const infoBox = document.getElementById("info-box");

const countries = {
  UnitedStates: {
    name: "United States",
    capital: "Washington, D.C.",
    leader: "Donald Trump",
    img: "images/us.webp",
    population: "341 million",
    area: "9,833,520 km&sup2;",
    language: "English",
    currency: "United States Dollar (USD, $)",
  },
  Canada: {
    name: "Canada",
    capital: "Ottawa",
    leader: "Justin Trudeau.",
    img: "images/canada.png",
    population: "40.8 million",
    area: "9,984,670 km&sup2;",
    language: "English and French",
    currency: "Canadian Dollar (CAD, $)",
  },
  MX: {
    name: "Mexico",
    capital: "Mexico City",
    leader: "Andrés Manuel López Obrador",
    img: "images/mexico.png",
    population: "128.9 million",
    area: "1,964,375 km&sup2;",
    language: "Spanish",
    currency: "Mexican Peso (MXN, $)",
  },
  AF: {
    name: "Afghanistan",
    capital: "Kabul",
    leader: "Hibatullah Akhundzada",
    img: "images/afghanistan-flag.jpg",
    population: "43.8 million",
    area: "652,860 km&sup2;",
    language: "Dari (Afghan Persian) & Pashto",
    currency: "Afghan afghani (AFN)",
  },
  AL: {
    name: "Albania",
    capital: "Tirana",
    leader: "Bajram Begaj",
    img: "images/albania-flag.webp",
    population: "2.8 million",
    area: "28,748 km&sup2;",
    language: "Albanian",
    currency: "Albanian lek (ALL)",
  },
  DZ: {
    name: "Algeria",
    capital: "Algiers",
    leader: "Abdelmadjid Tebboune",
    img: "images/algeria-flag.webp",
    population: "45 million",
    area: "2,381,741 km&sup2;",
    language: "Arabic and Berber",
    currency: "Algerian dinar (DZD)",
  },
  Angola: {
    name: "Angola",
    capital: "Luanda",
    leader: "João Lourenço",
    img: "images/angola-flag.webp",
    population: "35 million",
    area: "1,246,700 km&sup2;",
    language: "Portuguese",
    currency: "Angolan kwanza (AOA)",
  },
  AntiguaBarbuda: {
    name: "Antigua and Barbuda",
    capital: "Saint John's",
    leader: "Gaston Browne",
    img: "images/antiguabarbuda-flag.webp",
    population: "97,000",
    area: "442 km&sup2;",
    language: "English",
    currency: "East Caribbean dollar (XCD, $)",
  },
  Argentina: {
    name: "Argentina",
    capital: "Buenos Aires",
    leader: "Alberto Fernández",
    img: "images/argentina-flag.png",
    population: "45.8 million",
    area: "2,780,400 km&sup2;",
    language: "Spanish",
    currency: "Argentine peso (ARS, $)",
  },
  AM: {
    name: "Armenia",
    capital: "Yerevan",
    leader: "Vahagn Khachaturyan",
    img: "images/armenia-flag.webp",
    population: "3 million",
    area: "29,743 km&sup2;",
    language: "Armenian",
    currency: "Armenian dram (AMD)",
  },
  Australia: {
    name: "Australia",
    capital: "Canberra",
    leader: "Anthony Albanese",
    img: "images/australia-flag.png",
    population: "26 million",
    area: "7,692,024 km&sup2;",
    language: "English",
    currency: "Australian dollar (AUD, $)",
  },
  AT: {
    name: "Austria",
    capital: "Vienna",
    leader: "Karl Nehammer",
    img: "images/austria-flag.jpg",
    population: "9 million",
    area: "83,879 km&sup2;",
    language: "German",
    currency: "Euro (EUR, €)",
  },
  Azerbaijan: {
    name: "Azerbaijan",
    capital: "Baku",
    leader: "Ilham Aliyev",
    img: "images/azerbaijan-flag.webp",
    population: "10.1 million",
    area: "86,600 km&sup2;",
    language: "Azerbaijani",
    currency: "Azerbaijani manat (AZN, ₼)",
  },
  Bahamas: {
    name: "Bahamas",
    capital: "Nassau",
    leader: "Philip Davis",
    img: "images/bahamas-flag.jpeg",
    population: "412,000",
    area: "13,878 km²",
    language: "English",
    currency: "Bahamian Dollar (BSD, $)",
  },
  BH: {
    name: "Bahrain",
    capital: "Manama",
    leader: "Salman bin Hamad Al Khalifa",
    img: "images/bahrain.webp",
    population: "1.5 million",
    area: "778 km²",
    language: "Arabic",
    currency: "Bahraini Dinar (BHD)",
  },
  BD: {
    name: "Bangladesh",
    capital: "Dhaka",
    leader: "Sheikh Hasina",
    img: "images/bangladesh.webp",
    population: "173 million",
    area: "148,460 km²",
    language: "Bengali (Bangla)",
    currency: "Bangladeshi Taka (BDT)",
  },

  BB: {
    name: "Barbados",
    capital: "Bridgetown",
    leader: "Mia Mottley",
    img: "images/barbados.webp",
    population: "281,000",
    area: "430 km²",
    language: "English",
    currency: "Barbadian Dollar (BBD)",
  },

  BY: {
    name: "Belarus",
    capital: "Minsk",
    leader: "Alexander Lukashenko",
    img: "images/belarus.webp",
    population: "9.2 million",
    area: "207,600 km²",
    language: "Belarusian & Russian",
    currency: "Belarusian Ruble (BYN)",
  },

  BE: {
    name: "Belgium",
    capital: "Brussels",
    leader: "Alexander De Croo",
    img: "images/belgium.webp",
    population: "11.8 million",
    area: "30,689 km²",
    language: "Dutch, French & German",
    currency: "Euro (EUR)",
  },

  BZ: {
    name: "Belize",
    capital: "Belmopan",
    leader: "John Briceño",
    img: "images/belize.webp",
    population: "412,000",
    area: "22,966 km²",
    language: "English",
    currency: "Belize Dollar (BZD)",
  },
  BJ: {
    name: "Benin",
    capital: "Porto-Novo",
    leader: "Patrice Talon",
    img: "images/benin.webp",
    population: "13.7 million",
    area: "114,763 km²",
    language: "French",
    currency: "West African CFA franc (XOF)",
  },

  BT: {
    name: "Bhutan",
    capital: "Thimphu",
    leader: "Lotay Tshering",
    img: "images/bhutan.webp",
    population: "796,682",
    area: "38,394 km²",
    language: "Dzongkha",
    currency: "Bhutanese ngultrum (BTN)",
  },

  BO: {
    name: "Bolivia",
    capital: "Sucre",
    leader: "Luis Arce",
    img: "images/bolivia.webp",
    population: "12.1 million",
    area: "1,098,581 km²",
    language: "Spanish, Quechua, Aymara & others",
    currency: "Boliviano (BOB)",
  },

  BA: {
    name: "Bosnia and Herzegovina",
    capital: "Sarajevo",
    leader: "Šefik Džaferović / Željko Komšić / Milorad Dodik",
    img: "images/bosnia-and-herzegovina.webp",
    population: "3.3 million",
    area: "51,197 km²",
    language: "Bosnian, Croatian & Serbian",
    currency: "Convertible Mark (BAM)",
  },

  BW: {
    name: "Botswana",
    capital: "Gaborone",
    leader: "Mokgweetsi Masisi",
    img: "images/botswana.webp",
    population: "2.4 million",
    area: "582,000 km²",
    language: "English & Tswana",
    currency: "Botswana pula (BWP)",
  },
  BR: {
    name: "Brazil",
    capital: "Brasília",
    leader: "Luiz Inácio Lula da Silva",
    img: "images/brazil-flag.jpg",
    population: "212,812,405",
    area: "8,358,140 km²",
    language: "Portuguese",
    currency: "Brazilian real (BRL)",
  },

  BN: {
    name: "Brunei",
    capital: "Bandar Seri Begawan",
    leader: "Hassanal Bolkiah",
    img: "images/brunei-flag.jpg",
    population: "466,330",
    area: "5,270 km²",
    language: "Malay",
    currency: "Brunei dollar (BND)",
  },

  BG: {
    name: "Bulgaria",
    capital: "Sofia",
    leader: "Rumen Radev",
    img: "images/bulgaria-flag.jpg",
    population: "6,714,560",
    area: "108,560 km²",
    language: "Bulgarian",
    currency: "Bulgarian lev (BGN)",
  },

  BF: {
    name: "Burkina Faso",
    capital: "Ouagadougou",
    leader: "Ibrahim Traoré",
    img: "images/burkina-faso-flag.jpg",
    population: "24,074,580",
    area: "273,600 km²",
    language: "French",
    currency: "West African CFA franc (XOF)",
  },

  BI: {
    name: "Burundi",
    capital: "Gitega",
    leader: "Évariste Ndayishimiye",
    img: "images/burundi-flag.jpg",
    population: "12 million",
    area: "27,834 km²",
    language: "Kirundi, French",
    currency: "Burundian franc (BIF)",
  },
  CapeVerde: {
    name: "Cape Verde",
    capital: "Praia",
    leader: "José Maria Neves",
    img: "images/cabo-verde-flag.jpg",
    population: "527,326",
    area: "4,030 km²",
    language: "Portuguese",
    currency: "Cape Verdean escudo (CVE)",
  },

  KH: {
    name: "Cambodia",
    capital: "Phnom Penh",
    leader: "Hun Manet",
    img: "images/cambodia-flag.jpg",
    population: "17,847,982",
    area: "176,520 km²",
    language: "Khmer",
    currency: "Cambodian riel (KHR)",
  },

  CM: {
    name: "Cameroon",
    capital: "Yaoundé",
    leader: "Paul Biya",
    img: "images/cameroon-flag.jpg",
    population: "29,879,337",
    area: "472,710 km²",
    language: "French & English",
    currency: "Central African CFA franc (XAF)",
  },

  Canada: {
    name: "Canada",
    capital: "Ottawa",
    leader: "Justin Trudeau",
    img: "images/canada-flag.jpg",
    population: "40,126,723",
    area: "9,093,510 km²",
    language: "English & French",
    currency: "Canadian dollar (CAD)",
  },

  CF: {
    name: "Central African Republic",
    capital: "Bangui",
    leader: "Faustin-Archange Touadéra",
    img: "images/central-african-republic-flag.jpg",
    population: "5.6 million",
    area: "622,984 km²",
    language: "French & Sango",
    currency: "Central African CFA franc (XAF)",
  },
  TD: {
    name: "Chad",
    capital: "N'Djamena",
    leader: "Mahamat Déby",
    img: "images/chad-flag.jpg",
    population: "21,003,705",
    area: "1,259,200 km²",
    language: "French & Arabic",
    currency: "Central African CFA franc (XAF)",
  },

  Chile: {
    name: "Chile",
    capital: "Santiago",
    leader: "Gabriel Boric",
    img: "images/chile-flag.jpg",
    population: "19,859,921",
    area: "743,532 km²",
    language: "Spanish",
    currency: "Chilean peso (CLP)",
  },

  China: {
    name: "China",
    capital: "Beijing",
    leader: "Xi Jinping",
    img: "images/china-flag.jpg",
    population: "1,416,096,094",
    area: "9,388,211 km²",
    language: "Mandarin Chinese",
    currency: "Renminbi / Yuan (CNY)",
  },

  CO: {
    name: "Colombia",
    capital: "Bogotá",
    leader: "Gustavo Petro",
    img: "images/colombia-flag.jpg",
    population: "53,425,635",
    area: "1,109,500 km²",
    language: "Spanish",
    currency: "Colombian peso (COP)",
  },

  Comoros: {
    name: "Comoros",
    capital: "Moroni",
    leader: "Azali Assoumani",
    img: "images/comoros-flag.jpg",
    population: "882,847",
    area: "1,861 km²",
    language: "Comorian, Arabic & French",
    currency: "Comorian franc (KMF)",
  },

  CG: {
    name: "Republic of the Congo",
    capital: "Brazzaville",
    leader: "Denis Sassou Nguesso",
    img: "images/congo-brazzaville-flag.jpg",
    population: "6,484,437",
    area: "341,500 km²",
    language: "French",
    currency: "Central African CFA franc (XAF)",
  },

  CR: {
    name: "Costa Rica",
    capital: "San José",
    leader: "Rodrigo Chaves Robles",
    img: "images/costa-rica-flag.jpg",
    population: "5,152,950",
    area: "51,060 km²",
    language: "Spanish",
    currency: "Costa Rican colón (CRC)",
  },

  CI: {
    name: "Côte d'Ivoire",
    capital: "Yamoussoukro",
    leader: "Alassane Ouattara",
    img: "images/cote-divoire-flag.jpg",
    population: "32,711,547",
    area: "318,000 km²",
    language: "French",
    currency: "West African CFA franc (XOF)",
  },

  HR: {
    name: "Croatia",
    capital: "Zagreb",
    leader: "Zoran Milanović",
    img: "images/croatia-flag.jpg",
    population: "3,848,160",
    area: "55,960 km²",
    language: "Croatian",
    currency: "Euro (EUR)",
  },

  CU: {
    name: "Cuba",
    capital: "Havana",
    leader: "Miguel Díaz-Canel",
    img: "images/cuba-flag.jpg",
    population: "11,200,000",
    area: "109,884 km²",
    language: "Spanish",
    currency: "Cuban peso (CUP)",
  },
  Cyprus: {
    name: "Cyprus",
    capital: "Nicosia",
    leader: "Nikos Christodoulides",
    img: "images/cyprus-flag.jpg",
    population: "1,370,754",
    area: "9,240 km²",
    language: "Greek & Turkish",
    currency: "Euro (EUR)",
  },

  CZ: {
    name: "Czechia (Czech Republic)",
    capital: "Prague",
    leader: "Petr Pavel",
    img: "images/czechia-flag.jpg",
    population: "10,609,239",
    area: "77,240 km²",
    language: "Czech",
    currency: "Czech koruna (CZK)",
  },

  CD: {
    name: "Democratic Republic of the Congo",
    capital: "Kinshasa",
    leader: "Félix Tshisekedi",
    img: "images/dr-congo-flag.jpg",
    population: "112,832,473",
    area: "2,267,050 km²",
    language: "French, Lingala, Swahili, Kikongo, Tshiluba",
    currency: "Congolese franc (CDF)",
  },

  Denmark: {
    name: "Denmark",
    capital: "Copenhagen",
    leader: "Frederik X (Monarch) / Mette Frederiksen (PM)",
    img: "images/denmark-flag.jpg",
    population: "6,002,507",
    area: "42,430 km²",
    language: "Danish",
    currency: "Danish krone (DKK)",
  },

  DJ: {
    name: "Djibouti",
    capital: "Djibouti City",
    leader: "Ismaïl Omar Guelleh",
    img: "images/djibouti-flag.jpg",
    population: "1,184,076",
    area: "23,180 km²",
    language: "French & Arabic",
    currency: "Djiboutian franc (DJF)",
  },

  DM: {
    name: "Dominica",
    capital: "Roseau",
    leader: "Charles Savarin (President) / Roosevelt Skerrit (PM)",
    img: "images/dominica-flag.jpg",
    population: "65,871",
    area: "750 km²",
    language: "English",
    currency: "Eastern Caribbean dollar (XCD)",
  },

  DO: {
    name: "Dominican Republic",
    capital: "Santo Domingo",
    leader: "Luis Abinader",
    img: "images/dominican-republic-flag.jpg",
    population: "11,520,487",
    area: "48,320 km²",
    language: "Spanish",
    currency: "Dominican peso (DOP)",
  },

  EC: {
    name: "Ecuador",
    capital: "Quito",
    leader: "Daniel Noboa",
    img: "images/ecuador-flag.jpg",
    population: "18,289,896",
    area: "248,360 km²",
    language: "Spanish",
    currency: "United States Dollar (USD)",
  },

  EG: {
    name: "Egypt",
    capital: "Cairo",
    leader: "Abdel Fattah el-Sisi",
    img: "images/egypt-flag.jpg",
    population: "118,365,995",
    area: "995,450 km²",
    language: "Arabic",
    currency: "Egyptian pound (EGP)",
  },

  SV: {
    name: "El Salvador",
    capital: "San Salvador",
    leader: "Nayib Bukele",
    img: "images/el-salvador-flag.jpg",
    population: "6,364,943",
    area: "20,720 km²",
    language: "Spanish",
    currency: "United States Dollar (USD) & Bitcoin (BTC)",
  },
  GQ: {
    name: "Equatorial Guinea",
    capital: "Malabo (official) / Ciudad de la Paz (planned)",
    leader: "Teodoro Obiang Nguema Mbasogo",
    img: "images/equatorial-guinea-flag.jpg",
    population: "1,938,431",
    area: "28,050 km²",
    language: "Spanish, French, Portuguese",
    currency: "Central African CFA franc (XAF)",
  },

  ER: {
    name: "Eritrea",
    capital: "Asmara",
    leader: "Isaias Afwerki",
    img: "images/eritrea-flag.jpg",
    population: "3,607,003",
    area: "101,000 km²",
    language: "Tigrinya, Arabic, English",
    currency: "Eritrean nakfa (ERN)",
  },

  EE: {
    name: "Estonia",
    capital: "Tallinn",
    leader: "Alar Karis",
    img: "images/estonia-flag.jpg",
    population: "1,344,232",
    area: "42,390 km²",
    language: "Estonian",
    currency: "Euro (EUR)",
  },

  SZ: {
    name: "Eswatini (Swaziland)",
    capital: "Mbabane (administrative) / Lobamba (royal & legislative)",
    leader: "King Mswati III",
    img: "images/eswatini-flag.jpg",
    population: "1,256,174",
    area: "17,200 km²",
    language: "Swazi & English",
    currency: "Lilangeni (SZL)",
  },

  ET: {
    name: "Ethiopia",
    capital: "Addis Ababa",
    leader: "Sahle-Work Zewde (President) / Abiy Ahmed (PM)",
    img: "images/ethiopia-flag.jpg",
    population: "135,472,051",
    area: "1,000,000 km²",
    language: "Amharic (official) + many regional languages",
    currency: "Ethiopian birr (ETB)",
  },

  Fiji: {
    name: "Fiji",
    capital: "Suva",
    leader: "Wiliame Katonivere",
    img: "images/fiji-flag.jpg",
    population: "933,154",
    area: "18,270 km²",
    language: "Fijian, Hindi, English",
    currency: "Fijian dollar (FJD)",
  },

  FI: {
    name: "Finland",
    capital: "Helsinki",
    leader: "Alexander Stubb",
    img: "images/finland-flag.jpg",
    population: "5,623,329",
    area: "303,890 km²",
    language: "Finnish & Swedish",
    currency: "Euro (EUR)",
  },

  France: {
    name: "France",
    capital: "Paris",
    leader: "Emmanuel Macron",
    img: "images/france-flag.jpg",
    population: "66,650,804",
    area: "547,557 km²",
    language: "French",
    currency: "Euro (EUR)",
  },

  GA: {
    name: "Gabon",
    capital: "Libreville",
    leader: "Brice Oligui Nguema",
    img: "images/gabon-flag.jpg",
    population: "2,593,130",
    area: "257,670 km²",
    language: "French",
    currency: "Central African CFA franc (XAF)",
  },

  GM: {
    name: "The Gambia",
    capital: "Banjul",
    leader: "Adama Barrow",
    img: "images/gambia-flag.jpg",
    population: "2,773,168",
    area: "10,120 km²",
    language: "English",
    currency: "Gambian dalasi (GMD)",
  },
  GE: {
    name: "Georgia",
    capital: "Tbilisi",
    leader: "Salome Zourabichvili (President) / Irakli Garibashvili (PM)",
    img: "images/georgia-flag.jpg",
    population: "3,806,671",
    area: "69,490 km²",
    language: "Georgian",
    currency: "Georgian lari (GEL)",
  },

  DE: {
    name: "Germany",
    capital: "Berlin",
    leader: "Frank-Walter Steinmeier (President) / Olaf Scholz (Chancellor)",
    img: "images/germany-flag.jpg",
    population: "84,075,075",
    area: "348,560 km²",
    language: "German",
    currency: "Euro (EUR)",
  },

  GH: {
    name: "Ghana",
    capital: "Accra",
    leader: "Nana Akufo-Addo",
    img: "images/ghana-flag.jpg",
    population: "35,064,272",
    area: "227,540 km²",
    language: "English",
    currency: "Ghanaian cedi (GHS)",
  },

  Greece: {
    name: "Greece",
    capital: "Athens",
    leader: "Katerina Sakellaropoulou (President) / Kyriakos Mitsotakis (PM)",
    img: "images/greece-flag.jpg",
    population: "9,938,844",
    area: "128,900 km²",
    language: "Greek",
    currency: "Euro (EUR)",
  },

  GD: {
    name: "Grenada",
    capital: "St. George's",
    leader: "Dame Cécile La Grenade (Governor-General) / Dickon Mitchell (PM)",
    img: "images/grenada-flag.jpg",
    population: "117,303",
    area: "340 km²",
    language: "English",
    currency: "Eastern Caribbean dollar (XCD)",
  },

  GT: {
    name: "Guatemala",
    capital: "Guatemala City",
    leader: "Alejandro Giammattei",
    img: "images/guatemala-flag.jpg",
    population: "18,687,881",
    area: "107,160 km²",
    language: "Spanish",
    currency: "Guatemalan quetzal (GTQ)",
  },

  GN: {
    name: "Guinea",
    capital: "Conakry",
    leader: "Mamady Doumbouya (Interim)",
    img: "images/guinea-flag.jpg",
    population: "15,099,727",
    area: "245,720 km²",
    language: "French",
    currency: "Guinean franc (GNF)",
  },

  GW: {
    name: "Guinea-Bissau",
    capital: "Bissau",
    leader: "Umaro Sissoco Embaló",
    img: "images/guinea-bissau-flag.jpg",
    population: "2,249,515",
    area: "28,120 km²",
    language: "Portuguese",
    currency: "West African CFA franc (XOF)",
  },

  GY: {
    name: "Guyana",
    capital: "Georgetown",
    leader: "Irfaan Ali",
    img: "images/guyana-flag.jpg",
    population: "835,986",
    area: "196,850 km²",
    language: "English",
    currency: "Guyanese dollar (GYD)",
  },

  HT: {
    name: "Haiti",
    capital: "Port-au-Prince",
    leader: "Ariel Henry (Prime Minister / Acting President)",
    img: "images/haiti-flag.jpg",
    population: "11,402,528",
    area: "27,750 km²",
    language: "French & Haitian Creole",
    currency: "Haitian gourde (HTG)",
  },

  HN: {
    name: "Honduras",
    capital: "Tegucigalpa",
    leader: "Xiomara Castro",
    img: "images/honduras-flag.jpg",
    population: "11,005,850",
    area: "111,890 km²",
    language: "Spanish",
    currency: "Honduran lempira (HNL)",
  },

  HU: {
    name: "Hungary",
    capital: "Budapest",
    leader: "Katalin Novák",
    img: "images/hungary-flag.jpg",
    population: "9,632,287",
    area: "90,530 km²",
    language: "Hungarian",
    currency: "Hungarian forint (HUF)",
  },

  IS: {
    name: "Iceland",
    capital: "Reykjavík",
    leader: "Guðni Th. Jóhannesson",
    img: "images/iceland-flag.jpg",
    population: "398,266",
    area: "100,250 km²",
    language: "Icelandic",
    currency: "Icelandic króna (ISK)",
  },

  IN: {
    name: "India",
    capital: "New Delhi",
    leader: "Droupadi Murmu (President) / Narendra Modi (PM)",
    img: "images/india-flag.jpg",
    population: "1,463,865,525",
    area: "2,973,190 km²",
    language: "Hindi & English (official) + regional languages",
    currency: "Indian rupee (INR)",
  },

  Indonesia: {
    name: "Indonesia",
    capital: "Jakarta",
    leader: "Joko Widodo",
    img: "images/indonesia-flag.webp",
    population: "285,721,236",
    area: "1,811,570 km²",
    language: "Indonesian",
    currency: "Indonesian rupiah (IDR)",
  },

  IR: {
    name: "Iran",
    capital: "Tehran",
    leader: "Ebrahim Raisi",
    img: "images/iran-flag.jpg",
    population: "92,417,681",
    area: "1,628,550 km²",
    language: "Persian (Farsi)",
    currency: "Iranian rial (IRR)",
  },

  IQ: {
    name: "Iraq",
    capital: "Baghdad",
    leader: "Abdul Latif Rashid (President) / Mohammed Shia' Al Sudani (PM)",
    img: "images/iraq-flag.jpg",
    population: "47,020,774",
    area: "434,320 km²",
    language: "Arabic & Kurdish",
    currency: "Iraqi dinar (IQD)",
  },

  IE: {
    name: "Ireland",
    capital: "Dublin",
    leader: "Michael D. Higgins",
    img: "images/ireland-flag.jpg",
    population: "5,308,039",
    area: "68,890 km²",
    language: "Irish & English",
    currency: "Euro (EUR)",
  },

  IL: {
    name: "Israel",
    capital: "Jerusalem",
    leader: "Isaac Herzog (President) / Benjamin Netanyahu (PM)",
    img: "images/israel-flag.jpg",
    population: "9,565,080",
    area: "22,145 km²",
    language: "Hebrew & Arabic",
    currency: "Israeli new shekel (ILS)",
  },
  Italy: {
    name: "Italy",
    capital: "Rome",
    leader: "Sergio Mattarella (President) / Giorgia Meloni (PM)",
    img: "images/italy-flag.jpg",
    population: "59,146,260",
    area: "294,140 km²",
    language: "Italian",
    currency: "Euro (EUR)",
  },

  JM: {
    name: "Jamaica",
    capital: "Kingston",
    leader: "Dame Paula-Mae Weekes (Governor-General) / Andrew Holness (PM)",
    img: "images/jamaica-flag.jpg",
    population: "2,837,077",
    area: "10,830 km²",
    language: "English",
    currency: "Jamaican dollar (JMD)",
  },

  Japan: {
    name: "Japan",
    capital: "Tokyo",
    leader: "Emperor Naruhito / Fumio Kishida (PM)",
    img: "images/japan-flag.webp",
    population: "123,103,479",
    area: "364,555 km²",
    language: "Japanese",
    currency: "Japanese yen (JPY)",
  },

  JO: {
    name: "Jordan",
    capital: "Amman",
    leader: "King Abdullah II",
    img: "images/jordan-flag.jpg",
    population: "11,520,684",
    area: "88,780 km²",
    language: "Arabic",
    currency: "Jordanian dinar (JOD)",
  },

  KZ: {
    name: "Kazakhstan",
    capital: "Astana",
    leader: "Kassym-Jomart Tokayev",
    img: "images/kazakhstan-flag.jpg",
    population: "20,843,754",
    area: "2,699,700 km²",
    language: "Kazakh & Russian",
    currency: "Kazakhstani tenge (KZT)",
  },

  KE: {
    name: "Kenya",
    capital: "Nairobi",
    leader: "William Ruto",
    img: "images/kenya-flag.jpg",
    population: "57,532,493",
    area: "569,140 km²",
    language: "English & Swahili",
    currency: "Kenyan shilling (KES)",
  },

  KW: {
    name: "Kuwait",
    capital: "Kuwait City",
    leader: "Nawaf Al-Ahmad Al-Jaber Al-Sabah",
    img: "images/kuwait-flag.jpg",
    population: "5,026,078",
    area: "17,820 km²",
    language: "Arabic",
    currency: "Kuwaiti dinar (KWD)",
  },

  KG: {
    name: "Kyrgyzstan",
    capital: "Bishkek",
    leader: "Sadyr Japarov",
    img: "images/kyrgyzstan-flag.jpg",
    population: "7,295,034",
    area: "191,800 km²",
    language: "Kyrgyz & Russian",
    currency: "Kyrgyzstani som (KGS)",
  },

  LA: {
    name: "Laos",
    capital: "Vientiane",
    leader: "Thongloun Sisoulith",
    img: "images/laos-flag.jpg",
    population: "7,379,358",
    area: "237,955 km²",
    language: "Lao",
    currency: "Lao kip (LAK)",
  },
  LV: {
    name: "Latvia",
    capital: "Riga",
    leader: "Edgars Rinkēvičs (President)",
    img: "images/latvia-flag.jpg",
    population: "1,853,559",
    area: "62,200 km²",
    language: "Latvian",
    currency: "Euro (EUR)",
  },

  LB: {
    name: "Lebanon",
    capital: "Beirut",
    leader: "Michel Aoun",
    img: "images/lebanon-flag.jpg",
    population: "5,849,421",
    area: "10,230 km²",
    language: "Arabic",
    currency: "Lebanese pound (LBP)",
  },

  LS: {
    name: "Lesotho",
    capital: "Maseru",
    leader: "Letsie III",
    img: "images/lesotho-flag.jpg",
    population: "2,363,325",
    area: "30,360 km²",
    language: "Sesotho & English",
    currency: "Lesotho loti (LSL)",
  },

  LR: {
    name: "Liberia",
    capital: "Monrovia",
    leader: "George Weah",
    img: "images/liberia-flag.jpg",
    population: "5,731,206",
    area: "96,320 km²",
    language: "English",
    currency: "Liberian dollar (LRD)",
  },

  LY: {
    name: "Libya",
    capital: "Tripoli",
    leader:
      "Mohammed al-Menfi (Presidential Council) / Abdul Hamid Dbeibeh (PM)",
    img: "images/libya-flag.jpg",
    population: "7,458,555",
    area: "1,759,540 km²",
    language: "Arabic",
    currency: "Libyan dinar (LYD)",
  },
  LT: {
    name: "Lithuania",
    capital: "Vilnius",
    leader: "Gitanas Nausėda",
    img: "images/lithuania-flag.jpg",
    population: "2,795,680",
    area: "65,300 km²",
    language: "Lithuanian",
    currency: "Euro (EUR)",
  },
  LU: {
  name: "Luxembourg",
  capital: "Luxembourg City",
  leader: "Xavier Bettel (Prime Minister) / Henri (Grand Duke)",
  img: "images/luxembourg-flag.jpg",
  population: "680,453",
  area: "2,590 km²",
  language: "Luxembourgish, French, German",
  currency: "Euro (EUR)"
},

MG: {
  name: "Madagascar",
  capital: "Antananarivo",
  leader: "Andry Rajoelina",
  img: "images/madagascar-flag.jpg",
  population: "32,740,678",
  area: "581,795 km²",
  language: "Malagasy & French",
  currency: "Malagasy ariary (MGA)"
},

MW: {
  name: "Malawi",
  capital: "Lilongwe",
  leader: "Lazarus Chakwera",
  img: "images/malawi-flag.jpg",
  population: "22,216,120",
  area: "94,280 km²",
  language: "English & Chichewa",
  currency: "Malawian kwacha (MWK)"
},

Malaysia: {
  name: "Malaysia",
  capital: "Kuala Lumpur",
  leader: "Anwar Ibrahim (Prime Minister)",
  img: "images/malaysia-flag.jpg",
  population: "35,977,838",
  area: "328,550 km²",
  language: "Malay",
  currency: "Malaysian ringgit (MYR)"
},


ML: {
  name: "Mali",
  capital: "Bamako",
  leader: "Assimi Goïta",
  img: "images/mali-flag.jpg",
  population: "25,198,821",
  area: "1,220,190 km²",
  language: "French",
  currency: "West African CFA franc (XOF)"
},

Malta: {
  name: "Malta",
  capital: "Valletta",
  leader: "Robert Abela",
  img: "images/malta-flag.jpg",
  population: "545,405",
  area: "320 km²",
  language: "Maltese & English",
  currency: "Euro (EUR)"
},


MR: {
  name: "Mauritania",
  capital: "Nouakchott",
  leader: "Mohamed Ould Ghazouani",
  img: "images/mauritania-flag.jpg",
  population: "5,315,065",
  area: "1,030,700 km²",
  language: "Arabic",
  currency: "Mauritanian ouguiya (MRU)"
},

Mauritius: {
  name: "Mauritius",
  capital: "Port Louis",
  leader: "Pravind Jugnauth",
  img: "images/mauritius-flag.jpg",
  population: "1,308,000",
  area: "2,040 km²",
  language: "English, French, Mauritian Creole",
  currency: "Mauritian rupee (MUR)"
},
Micronesia: {
  name: "Micronesia",
  capital: "Palikir",
  leader: "Wesley Simina",
  img: "images/fm.webp",
  population: "113,683",
  area: "700 km²",
  language: "English",
  currency: "United States Dollar (USD)"
},

MD: {
  name: "Moldova",
  capital: "Chișinău",
  leader: "Maia Sandu",
  img: "images/md.webp",
  population: "2,996,106",
  area: "32,850 km²",
  language: "Romanian",
  currency: "Moldovan leu (MDL)"
},

MN: {
  name: "Mongolia",
  capital: "Ulaanbaatar",
  leader: "Ukhnaagiin Khürelsükh",
  img: "images/mn.webp",
  population: "3,517,100",
  area: "1,553,560 km²",
  language: "Mongolian",
  currency: "Mongolian tögrög (MNT)"
},

ME: {
  name: "Montenegro",
  capital: "Podgorica",
  leader: "Jakov Milatović",
  img: "images/me.webp",
  population: "632,729",
  area: "13,450 km²",
  language: "Montenegrin",
  currency: "Euro (EUR)"
},

MA: {
  name: "Morocco",
  capital: "Rabat",
  leader: "King Mohammed VI",
  img: "images/ma.webp",
  population: "38,430,770",
  area: "446,300 km²",
  language: "Arabic & Berber",
  currency: "Moroccan dirham (MAD)"
},

MZ: {
  name: "Mozambique",
  capital: "Maputo",
  leader: "Filipe Nyusi",
  img: "images/mz.webp",
  population: "35,631,653",
  area: "786,380 km²",
  language: "Portuguese",
  currency: "Mozambican metical (MZN)"
},

MM: {
  name: "Myanmar",
  capital: "Naypyidaw",
  leader: "Min Aung Hlaing",
  img: "images/mm.webp",
  population: "54,850,648",
  area: "653,290 km²",
  language: "Burmese",
  currency: "Burmese kyat (MMK)"
},

NA: {
  name: "Namibia",
  capital: "Windhoek",
  leader: "Nangolo Mbumba",
  img: "images/na.webp",
  population: "2,604,172",
  area: "823,290 km²",
  language: "English",
  currency: "Namibian dollar (NAD)"
},
NP: {
  name: "Nepal",
  capital: "Kathmandu",
  leader: "Ram Chandra Paudel (President) / Pushpa Kamal Dahal (PM)",
  img: "images/np-flag.jpg",
  population: "29,618,118",
  area: "143,350 km²",
  language: "Nepali",
  currency: "Nepalese rupee (NPR)"
},

NL: {
  name: "Netherlands",
  capital: "Amsterdam / The Hague (seat of government)",
  leader: "Willem-Alexander",
  img: "images/nl-flag.jpg",
  population: "18,346,819",
  area: "33,720 km²",
  language: "Dutch",
  currency: "Euro (EUR)"
},

NewZealand: {
  name: "New Zealand",
  capital: "Wellington",
  leader: "Cindy Kiro (Governor-General) / Christopher Luxon (PM)",
  img: "images/nz-flag.jpg",
  population: "5,251,899",
  area: "263,310 km²",
  language: "English, Māori",
  currency: "New Zealand dollar (NZD)"
},

NI: {
  name: "Nicaragua",
  capital: "Managua",
  leader: "Daniel Ortega",
  img: "images/ni-flag.jpg",
  population: "7,007,502",
  area: "120,340 km²",
  language: "Spanish",
  currency: "Nicaraguan córdoba (NIO)"
},

NE: {
  name: "Niger",
  capital: "Niamey",
  leader: "Mohamed Bazoum",
  img: "images/ne-flag.jpg",
  population: "27,917,831",
  area: "1,266,700 km²",
  language: "French",
  currency: "West African CFA franc (XOF)"
},

NG: {
  name: "Nigeria",
  capital: "Abuja",
  leader: "Bola Tinubu",
  img: "images/ng-flag.jpg",
  population: "237,527,782",
  area: "910,770 km²",
  language: "English",
  currency: "Nigerian naira (NGN)"
},

KP: {
  name: "North Korea",
  capital: "Pyongyang",
  leader: "Kim Jong-un",
  img: "images/kp-flag.jpg",
  population: "26,571,036",
  area: "120,410 km²",
  language: "Korean",
  currency: "North Korean won (KPW)"
},

MK: {
  name: "North Macedonia",
  capital: "Skopje",
  leader: "Stevo Pendarovski (President) / Dimitar Kovačevski (PM)",
  img: "images/mk-flag.jpg",
  population: "1,813,791",
  area: "25,220 km²",
  language: "Macedonian",
  currency: "Macedonian denar (MKD)"
},

Norway: {
  name: "Norway",
  capital: "Oslo",
  leader: "King Harald V / Jonas Gahr Støre (PM)",
  img: "images/no-flag.jpg",
  population: "5,623,071",
  area: "365,268 km²",
  language: "Norwegian",
  currency: "Norwegian krone (NOK)"
},

Oman: {
  name: "Oman",
  capital: "Muscat",
  leader: "Haitham bin Tariq",
  img: "images/om-flag.jpg",
  population: "4,561,194",
  area: "309,500 km²",
  language: "Arabic",
  currency: "Omani rial (OMR)"
},
PK: {
  name: "Pakistan",
  capital: "Islamabad",
  leader: "Asif Ali Zardari (President) / Shehbaz Sharif (PM)",
  img: "images/pk-flag.jpg",
  population: "255,219,554",
  area: "770,880 km²",
  language: "Urdu, English",
  currency: "Pakistani rupee (PKR)"
},

PW: {
  name: "Palau",
  capital: "Ngerulmud",
  leader: "Surangel Whipps Jr.",
  img: "images/pw-flag.jpg",
  population: "17,663",
  area: "460 km²",
  language: "Palauan, English",
  currency: "United States dollar (USD)"
},

PS: {
  name: "Palestine",
  capital: "East Jerusalem (claimed) / Ramallah (administrative)",
  leader: "Mahmoud Abbas",
  img: "images/ps-flag.jpg",
  population: "5,589,623",
  area: "6,020 km²",
  language: "Arabic",
  currency: "Israeli new shekel (ILS), Jordanian dinar (JOD)"
},

PA: {
  name: "Panama",
  capital: "Panama City",
  leader: "José Raúl Mulino",
  img: "images/pa-flag.jpg",
  population: "4,571,189",
  area: "74,340 km²",
  language: "Spanish",
  currency: "Panamanian balboa (PAB) & US dollar (USD)"
},

PapuaNewGuinea: {
  name: "Papua New Guinea",
  capital: "Port Moresby",
  leader: "Bob Dadae (Governor-General) / James Marape (PM)",
  img: "images/pg-flag.jpg",
  population: "10,762,817",
  area: "452,860 km²",
  language: "English, Tok Pisin, Hiri Motu",
  currency: "Papua New Guinean kina (PGK)"
},

PY: {
  name: "Paraguay",
  capital: "Asunción",
  leader: "Santiago Peña",
  img: "images/py-flag.jpg",
  population: "7,013,078",
  area: "397,300 km²",
  language: "Spanish, Guaraní",
  currency: "Paraguayan guaraní (PYG)"
},

PE: {
  name: "Peru",
  capital: "Lima",
  leader: "Dina Boluarte",
  img: "images/pe-flag.jpg",
  population: "34,576,665",
  area: "1,280,000 km²",
  language: "Spanish, Quechua, Aymara",
  currency: "Peruvian sol (PEN)"
},

Philippines: {
  name: "Philippines",
  capital: "Manila",
  leader: "Ferdinand Marcos Jr.",
  img: "images/ph-flag.jpg",
  population: "116,786,962",
  area: "298,170 km²",
  language: "Filipino, English",
  currency: "Philippine peso (PHP)"
},

PL: {
  name: "Poland",
  capital: "Warsaw",
  leader: "Andrzej Duda (President) / Donald Tusk (PM)",
  img: "images/pl-flag.jpg",
  population: "38,140,910",
  area: "306,230 km²",
  language: "Polish",
  currency: "Polish złoty (PLN)"
},

PT: {
  name: "Portugal",
  capital: "Lisbon",
  leader: "Marcelo Rebelo de Sousa (President) / Luís Montenegro (PM)",
  img: "images/pt-flag.jpg",
  population: "10,467,366",
  area: "92,226 km²",
  language: "Portuguese",
  currency: "Euro (EUR)"
},
NR: {
  name: "Nauru",
  capital: "Yaren (de facto)",
  leader: "Lionel Aingimea",
  img: "images/nr-flag.jpg",
  population: "10,876",
  area: "21 km²",
  language: "Nauruan, English",
  currency: "Australian Dollar (AUD)",
},
QA: {
  name: "Qatar",
  capital: "Doha",
  leader: "Sheikh Tamim bin Hamad Al Thani",
  img: "images/qa-flag.jpg",
  population: "3,115,889",
  area: "11,610 km²",
  language: "Arabic",
  currency: "Qatari Riyal (QAR)",
},

RO: {
  name: "Romania",
  capital: "Bucharest",
  leader: "Klaus Iohannis",
  img: "images/ro-flag.jpg",
  population: "18,908,650",
  area: "230,170 km²",
  language: "Romanian",
  currency: "Romanian Leu (RON)",
},

Russia: {
  name: "Russia",
  capital: "Moscow",
  leader: "Vladimir Putin",
  img: "images/ru-flag.jpg",
  population: "143,997,393",
  area: "16,376,870 km²",
  language: "Russian",
  currency: "Russian Ruble (RUB)",
},

RW: {
  name: "Rwanda",
  capital: "Kigali",
  leader: "Paul Kagame",
  img: "images/rw-flag.jpg",
  population: "14,569,341",
  area: "24,670 km²",
  language: "Kinyarwanda, French, English",
  currency: "Rwandan Franc (RWF)",
},

SaintKittsandNevis: {
  name: "Saint Kitts and Nevis",
  capital: "Basseterre",
  leader: "Terrance Drew",
  img: "images/kn-flag.jpg",
  population: "46,922",
  area: "260 km²",
  language: "English",
  currency: "East Caribbean Dollar (XCD)",
},

LC: {
  name: "Saint Lucia",
  capital: "Castries",
  leader: "Philip J. Pierre",
  img: "images/lc-flag.jpg",
  population: "180,149",
  area: "610 km²",
  language: "English",
  currency: "East Caribbean Dollar (XCD)",
},

VC: {
  name: "Saint Vincent and the Grenadines",
  capital: "Kingstown",
  leader: "Ralph Gonsalves",
  img: "images/vc-flag.jpg",
  population: "99,924",
  area: "390 km²",
  language: "English",
  currency: "East Caribbean Dollar (XCD)",
},
Samoa: {
  name: "Samoa",
  capital: "Apia",
  leader: "Fiame Naomi Mataʻafa",
  img: "images/ws-flag.jpg",
  population: "219,306",
  area: "2,830 km²",
  language: "Samoan, English",
  currency: "Samoan Tala (WST)",
},
SaoTomeandPrincipe: {
  name: "Sao Tome and Principe",
  capital: "São Tomé",
  leader: "Carlos Vila Nova",
  img: "images/st-flag.jpg",
  population: "227,380",
  area: "960 km²",
  language: "Portuguese",
  currency: "Dobra (STN)",
},
SA: {
  name: "Saudi Arabia",
  capital: "Riyadh",
  leader: "King Salman bin Abdulaziz Al Saud",
  img: "images/sa-flag.jpg",
  population: "34,566,328",
  area: "2,149,690 km²",
  language: "Arabic",
  currency: "Saudi Riyal (SAR)",
},

SN: {
  name: "Senegal",
  capital: "Dakar",
  leader: "Macky Sall",
  img: "images/sn-flag.jpg",
  population: "18,931,966",
  area: "192,530 km²",
  language: "French",
  currency: "West African CFA Franc (XOF)",
},

RS: {
  name: "Serbia",
  capital: "Belgrade",
  leader: "Aleksandar Vučić",
  img: "images/rs-flag.jpg",
  population: "6,689,039",
  area: "87,460 km²",
  language: "Serbian",
  currency: "Serbian Dinar (RSD)",
},

Seychelles: {
  name: "Seychelles",
  capital: "Victoria",
  leader: "Wavel Ramkalawan",
  img: "images/sc-flag.jpg",
  population: "132,779",
  area: "460 km²",
  language: "Seychellois Creole, English, French",
  currency: "Seychellois Rupee (SCR)",
},

SL: {
  name: "Sierra Leone",
  capital: "Freetown",
  leader: "Julius Maada Bio",
  img: "images/sl-flag.jpg",
  population: "8,819,794",
  area: "72,180 km²",
  language: "English",
  currency: "Sierra Leonean Leone (SLE)",
},

SK: {
  name: "Slovakia",
  capital: "Bratislava",
  leader: "Peter Pellegrini",
  img: "images/sk-flag.jpg",
  population: "5,474,881",
  area: "48,088 km²",
  language: "Slovak",
  currency: "Euro (EUR)",
},

SI: {
  name: "Slovenia",
  capital: "Ljubljana",
  leader: "Nataša Pirc Musar",
  img: "images/si-flag.jpg",
  population: "2,117,072",
  area: "20,140 km²",
  language: "Slovene",
  currency: "Euro (EUR)",
},

SolomonIslands: {
  name: "Solomon Islands",
  capital: "Honiara",
  leader: "Manasseh Sogavare",
  img: "images/sb-flag.jpg",
  population: "838,645",
  area: "27,990 km²",
  language: "English",
  currency: "Solomon Islands Dollar (SBD)",
},

SO: {
  name: "Somalia",
  capital: "Mogadishu",
  leader: "Hassan Sheikh Mohamud",
  img: "images/so-flag.jpg",
  population: "18,143,378",
  area: "637,657 km²",
  language: "Somali, Arabic",
  currency: "Somali Shilling (SOS)",
},
zA: {
    name: "South Africa",
    capital: "Pretoria",
    leader: "Cyril Ramaphosa",
    img: "images/south-africa.webp",
    population: "64,747,319",
    area: "1,213,090 km&sup2;",
    language: "Zulu, Xhosa, Afrikaans, English, others",
    currency: "South African Rand (ZAR, R)",
},
KR: {
    name: "South Korea",
    capital: "Seoul",
    leader: "Yoon Suk-yeol",
    img: "images/south-korea.webp",
    population: "51,667,029",
    area: "97,230 km&sup2;",
    language: "Korean",
    currency: "South Korean won (KRW, ₩)",
},
SS: {
    name: "South Sudan",
    capital: "Juba",
    leader: "Salva Kiir Mayardit",
    img: "images/south-sudan.webp",
    population: "12,188,788",
    area: "610,952 km&sup2;",
    language: "English",
    currency: "South Sudanese pound (SSP)",
},
ES: {
    name: "Spain",
    capital: "Madrid",
    leader: "Pedro Sánchez",
    img: "images/spain.webp",
    population: "47,889,958",
    area: "498,800 km&sup2;",
    language: "Spanish",
    currency: "Euro (EUR, €)",
},
LK: {
    name: "Sri Lanka",
    capital: "Sri Jayawardenepura Kotte",
    leader: "Ranil Wickremesinghe",
    img: "images/sri-lanka.webp",
    population: "23,229,470",
    area: "62,710 km&sup2;",
    language: "Sinhala, Tamil",
    currency: "Sri Lankan rupee (LKR, Rs)",
},
SD: {
    name: "Sudan",
    capital: "Khartoum",
    leader: "Abdalla Hamdok (Acting)",
    img: "images/sudan.webp",
    population: "51,662,147",
    area: "1,765,048 km&sup2;",
    language: "Arabic, English",
    currency: "Sudanese pound (SDG)",
},
SR: {
    name: "Suriname",
    capital: "Paramaribo",
    leader: "Chan Santokhi",
    img: "images/suriname.webp",
    population: "639,850",
    area: "156,000 km&sup2;",
    language: "Dutch",
    currency: "Surinamese dollar (SRD, $)",
},
SE: {
    name: "Sweden",
    capital: "Stockholm",
    leader: "Ulf Kristersson",
    img: "images/sweden.webp",
    population: "10,656,633",
    area: "410,340 km&sup2;",
    language: "Swedish",
    currency: "Swedish krona (SEK, kr)",
},
CH: {
    name: "Switzerland",
    capital: "Bern",
    leader: "Alain Berset (President of the Confederation)",
    img: "images/switzerland.webp",
    population: "8,967,407",
    area: "39,516 km&sup2;",
    language: "German, French, Italian, Romansh",
    currency: "Swiss franc (CHF, Fr.)",
},
SY: {
    name: "Syria",
    capital: "Damascus",
    leader: "Bashar al-Assad",
    img: "images/syria.webp",
    population: "21,000,000",
    area: "185,180 km&sup2;",
    language: "Arabic",
    currency: "Syrian pound (SYP, £S)",
},
TJ: {
    name: "Tajikistan",
    capital: "Dushanbe",
    leader: "Emomali Rahmon",
    img: "images/tajikistan.webp",
    population: "10,786,734",
    area: "139,960 km&sup2;",
    language: "Tajik",
    currency: "Tajikistani somoni (TJS)",
},
TZ: {
    name: "Tanzania",
    capital: "Dodoma",
    leader: "Samia Suluhu Hassan",
    img: "images/tanzania.webp",
    population: "70,545,865",
    area: "885,800 km&sup2;",
    language: "Swahili, English",
    currency: "Tanzanian shilling (TZS)",
},
TH: {
    name: "Thailand",
    capital: "Bangkok",
    leader: "Srettha Thavisin (Prime Minister)",
    img: "images/thailand.webp",
    population: "71,619,863",
    area: "510,890 km&sup2;",
    language: "Thai",
    currency: "Thai baht (THB, ฿)",
},
TL: {
    name: "Timor-Leste",
    capital: "Dili",
    leader: "José Ramos-Horta",
    img: "images/timor-leste.webp",
    population: "1,418,517",
    area: "14,870 km&sup2;",
    language: "Tetum, Portuguese",
    currency: "United States dollar (USD, $)",
},
TG: {
    name: "Togo",
    capital: "Lomé",
    leader: "Faure Gnassingbé",
    img: "images/togo.webp",
    population: "9,721,608",
    area: "54,390 km&sup2;",
    language: "French",
    currency: "West African CFA franc (XOF, Fr)",
},
Tonga: {
    name: "Tonga",
    capital: "Nukuʻalofa",
    leader: "Tupou VI",
    img: "images/tonga.webp",
    population: "103,742",
    area: "720 km&sup2;",
    language: "Tongan, English",
    currency: "Tongan paʻanga (TOP, T$)",
},
TrinidadandTobago: {
    name: "Trinidad and Tobago",
    capital: "Port of Spain",
    leader: "Paula-Mae Weekes (President)",
    img: "images/trinidad-tobago.webp",
    population: "1,511,155",
    area: "5,130 km&sup2;",
    language: "English",
    currency: "Trinidad and Tobago dollar (TTD, $)",
},
TN: {
    name: "Tunisia",
    capital: "Tunis",
    leader: "Kais Saied",
    img: "images/tunisia.webp",
    population: "12,348,573",
    area: "155,360 km&sup2;",
    language: "Arabic",
    currency: "Tunisian dinar (TND)",
},
Turkey: {
    name: "Turkey",
    capital: "Ankara",
    leader: "Recep Tayyip Erdoğan",
    img: "images/turkey.webp",
    population: "87,685,426",
    area: "769,630 km&sup2;",
    language: "Turkish",
    currency: "Turkish lira (TRY, ₺)",
},
TM: {
    name: "Turkmenistan",
    capital: "Ashgabat",
    leader: "Serdar Berdimuhamedow",
    img: "images/turkmenistan.webp",
    population: "6,031,200",
    area: "488,100 km&sup2;",
    language: "Turkmen",
    currency: "Turkmenistan manat (TMT)",
},
MH: {
    name: "Marshall Islands",
    capital: "Majuro",
    leader: "David Kabua",
    img: "images/marshall-islands.webp",
    population: "36,282",
    area: "180 km&sup2;",
    language: "Marshallese, English",
    currency: "United States dollar (USD, $)",
},
MV: {
    name: "Maldives",
    capital: "Malé",
    leader: "Ibrahim Mohamed Solih",
    img: "images/maldives.webp",
    population: "529,676",
    area: "300 km&sup2;",
    language: "Dhivehi",
    currency: "Maldivian rufiyaa (MVR, .ރ)",
},

TV: {
    name: "Tuvalu",
    capital: "Funafuti",
    leader: "Charles III (Monarch)",
    img: "images/tuvalu.webp",
    population: "9,492",
    area: "30 km&sup2;",
    language: "Tuvaluan, English",
    currency: "Tuvaluan dollar (TVD), Australian dollar (AUD)",
},
UG: {
    name: "Uganda",
    capital: "Kampala",
    leader: "Yoweri Museveni",
    img: "images/uganda.webp",
    population: "51,384,894",
    area: "199,810 km&sup2;",
    language: "English, Swahili",
    currency: "Ugandan shilling (UGX)",
},
UA: {
    name: "Ukraine",
    capital: "Kyiv",
    leader: "Volodymyr Zelenskyy",
    img: "images/ukraine.webp",
    population: "38,980,376",
    area: "579,320 km&sup2;",
    language: "Ukrainian",
    currency: "Hryvnia (UAH, ₴)",
},
AE: {
    name: "United Arab Emirates",
    capital: "Abu Dhabi",
    leader: "Mohammed bin Zayed Al Nahyan",
    img: "images/uae.webp",
    population: "11,346,000",
    area: "83,600 km&sup2;",
    language: "Arabic",
    currency: "United Arab Emirates dirham (AED, د.إ)",
},
UnitedKingdom: {
    name: "United Kingdom",
    capital: "London",
    leader: "Charles III",
    img: "images/uk.webp",
    population: "69,551,332",
    area: "241,930 km&sup2;",
    language: "English",
    currency: "Pound sterling (GBP, £)",
},

UY: {
    name: "Uruguay",
    capital: "Montevideo",
    leader: "Luis Lacalle Pou",
    img: "images/uruguay.webp",
    population: "3,384,688",
    area: "175,020 km&sup2;",
    language: "Spanish",
    currency: "Uruguayan peso (UYU, $U)",
},
UZ: {
    name: "Uzbekistan",
    capital: "Tashkent",
    leader: "Shavkat Mirziyoyev",
    img: "images/uzbekistan.webp",
    population: "37,053,428",
    area: "425,400 km&sup2;",
    language: "Uzbek",
    currency: "Uzbekistani som (UZS)",
},
Vanuatu: {
    name: "Vanuatu",
    capital: "Port Vila",
    leader: "Nayuli Bulani (President)",
    img: "images/vanuatu.webp",
    population: "335,169",
    area: "12,190 km&sup2;",
    language: "Bislama, English, French",
    currency: "Vanuatu vatu (VUV, VT)",
},
VE: {
    name: "Venezuela",
    capital: "Caracas",
    leader: "Nicolás Maduro",
    img: "images/venezuela.webp",
    population: "28,704,954",
    area: "916,445 km&sup2;",
    language: "Spanish",
    currency: "Venezuelan bolívar (VES, Bs.S)",
},
VN: {
    name: "Vietnam",
    capital: "Hanoi",
    leader: "Vo Van Thuong",
    img: "images/vietnam.webp",
    population: "101,598,527",
    area: "310,070 km&sup2;",
    language: "Vietnamese",
    currency: "Vietnamese đồng (VND, ₫)",
},
YE: {
    name: "Yemen",
    capital: "Sana'a",
    leader: "Rashad al-Alimi",
    img: "images/yemen.webp",
    population: "41,773,878",
    area: "527,970 km&sup2;",
    language: "Arabic",
    currency: "Yemeni rial (YER, ﷼)",
},
ZM: {
    name: "Zambia",
    capital: "Lusaka",
    leader: "Hakainde Hichilema",
    img: "images/zambia.webp",
    population: "21,913,874",
    area: "743,390 km&sup2;",
    language: "English",
    currency: "Zambian kwacha (ZMW, ZK)",
},
ZW: {
    name: "Zimbabwe",
    capital: "Harare",
    leader: "Emmerson Mnangagwa",
    img: "images/zimbabwe.webp",
    population: "16,893,000",
    area: "390,757 km&sup2;",
    language: "English, Shona, Sindebele",
    currency: "Zimbabwean dollar (ZWL, $)",
},

};


document.querySelectorAll("svg path").forEach((element) => {
  element.addEventListener("click", (e) => {
    e.stopPropagation();

    const countryKey =
      element.id || element.getAttribute("name") || element.className.baseVal;
    if (!countryKey || !countries[countryKey]) return;

    const data = countries[countryKey];
    const { name, capital, leader, img, population, area, language, currency } =
      data;

    infoBox.innerHTML = `
      <div class="popup-content">
        <img src="${img}" alt="${name}" class="popup-sticker">
        <div class="popup-text">
          <strong>${name}</strong>
          <p>Capital: ${capital}</p>
          <p>Leader: ${leader}</p>
          <p>Population: ${population}</p>
          <p>Area: ${area}</p>
          <p>Language: ${language}</p>
          <p>Currency: ${currency}</p>
        </div>
      </div>
    `;
    const offsetX = 15,
      offsetY = 15;
    let left = e.pageX + offsetX;
    let top = e.pageY + offsetY;

    const boxWidth = infoBox.offsetWidth;
    const boxHeight = infoBox.offsetHeight;

    if (left + boxWidth > window.innerWidth) left = e.pageX - boxWidth - 10;
    if (top + boxHeight > window.innerHeight) top = e.pageY - boxHeight - 10;

    infoBox.style.left = left + "px";
    infoBox.style.top = top + "px";
    infoBox.style.display = "block";
    infoBox.classList.remove("hide");
    infoBox.classList.add("show");
  });
});


document.addEventListener("click", (e) => {
  if (!e.target.closest("path")) {
    infoBox.classList.remove("show");
    infoBox.classList.add("hide");
    setTimeout(() => (infoBox.style.display = "none"), 200);
  }
});
